Python driver IngresDBI Fixes Trac ticket #255 - embedded nulls in string type are lost. String fixes, ensure correct lengths are used, Unicode under Unix (UCS4/UTF32) works - basic re-org of string handling (to use the same code as used for decimal type) which happens to fix many bugs.
Fixes all previously failing tests.
Re-instates (NOtest_SimpleUnicodeBind) a previously failing test
that was not being run due to causing hangs in the test suite.
New tests added. One of which fails (so only one test fails in a
normal run now).

This change is basically a "String" fix and addressed many of the
reported issues with strings. The change itself is modeled on (and
uses) the code from revision [1880] decimal data type not sent or
received correctly. All send and fetch/get code used for strings
is the same as is used for decimal types (bind code and allocate
code is different though).

Implements working support for Unicode under Unix (or any platform
where wchar_t is not 2 bytes). Makes use of "native" Unicode
to Python Unicode functions, rather than using the encoding to
Unicode functions. I did look into continuing to use encode/decode
functions but utf32 support is not available until Python 2.6.x
(not sure of the sub number, utf32 support was back ported from
Python 3.x). See below for idear for cod that is not portable to
older releases of Python. NOTE the new implementation is actually
much faster if wchar_t size is the same as the Python Unicode size
(than using encode/decode functions).

    static char EncodingNameUTF16[] = "utf_16";
    static char EncodingNameUTF32[] = "utf_32"; /* FIXME not supported in python pre 3.x!! later versions of 2.6 have it */
    static char *unicodeEncodingName = EncodingNameUTF16;
    .....
    .....
        /* set encoding and unicode length here... */
        if (sizeof(SQLWCHAR) == 2)
            unicodeEncodingName = EncodingNameUTF16;
        else if (sizeof(SQLWCHAR) == 4)
            unicodeEncodingName = EncodingNameUTF32;
        else
            unicodeEncodingName = NULL; /* FIXME need error checking/raise error "Native Unicode encoding not handled" */



NOTE there is a performance penalty (space and time) using ODBC and
Python on platforms where wchar_t is not 2 bytes (and PyUnicode
is UTF16, which is the default build config for Python) due to
ODBC getting UCS2/UTF16 data from the DBMS, converting to UTF32,
then Python converting from UTF32 to UCS2/UTF16. This change
makes it clear that we really need extensions to our ODBC driver
to send/receive UCS2/UTF16 encoded data through ODBC. The reason
for this is that the Python driver really wants UCS2/UTF16 (ditto
the Perl DBD::ODBC driver). On platforms where "sizeof(wchar_t)
!= 2" our ODBC driver gets UCS2/UTF16 data from the DBMS server
across GCA and then converts to UCS4/UTF32, the Python driver then
converts that from UCS4/UTF32 back into UCS2/UTF16! This is a large
amount of processing that is needless.

Made use of PY_VERSION_HEX macro as Python 2.5 introduced minor
api changes for length types (for 64 bit support), to maintain
2.4 support PY_VERSION_HEX is being used to support either type of
length specifier (int or Py_ssize_t).

Added FIXME notes to dbproc code (need new tests).

There where a few places where uninitialized variables could have
been used, added initial variables where appropriate. There maybe
other places where this is needed.

For send bind parms, moved "if this is NULL set NULL flag" code to
beginning of loop to remove duplicate code.

When determining allocation size of strings, automatically allocate
space for NULL terminator. For VARCHAR this seems needless, however
SQLGetData null terminates strings, so the extra space is needed!

Now using orInd in IIDBI_DESCRIPTOR for string types.

Start of documenting trace flags/bitmask. Corrected mistake in
"folding" markers in trace for IIDBI_cursorExecute() as well as
trace type.

Added a few extra trace statements that helped me track down some
odd behaviors during testing.

New compile warning, either use type cast and then get:

dbi/ingresdbi.c: In function 'IIDBI_sendParameters':
dbi/ingresdbi.c:6180: warning: passing argument 1 of 'PyUnicodeUCS4_AsWideChar' from incompatible pointer type

            tmplength=PyUnicode_AsWideChar(PyUnicode_FromObject(elem), unicodeStr, PyUnicode_GetSize(elem));

This is under Linux with GCC 4.2.4 and appears to be due to a
missing function prototype for PyUnicodeUCS4_AsWideChar in the
Python headers for 2.4.

Under Windows:

dbi\ingresdbi.c(6180) : warning C4133: 'function' : incompatible types - from 'PyObject *' to 'PyUnicodeObject *'

This does not appear to be a legitimate error.

Or do not have type cast and get:

Linux:

dbi/ingresdbi.c: In function 'IIDBI_sendParameters':
dbi/ingresdbi.c:6181: warning: passing argument 1 of 'PyUnicodeUCS4_AsWideChar' from incompatible pointer type

Windows:

dbi\ingresdbi.c(6181) : warning C4133: 'function' : incompatible types - from 'PyObject *' to 'PyUnicodeObject *'

Which is a real warning, but I'm not sure if one is allowed to mix
"sub-classes" of PyObject in API calls in C (as it is C not C++
with inheritance).

Even with the compile warning I believe this code to be safer
and more correct than before. I'd rather tackle this problem as
a separate issue as this will need consulting with Python experts
outside of Ingres Corp (need to create a test mini/demo extension
showing the problem). Currently using the form with the type cast
(which looks like a Python SDK bug but needs more research).


--------
Test changes:

test_bug_Embedded_Nulls split into two seperate tests, one for
VARCHAR type the other for NVARCHAR (Unicode), new tests:
    test_bug_Embedded_NullsVarchar
    test_bug_Embedded_NullsUnicode

New tests based on test_bug_Embedded_Nulls that is for bind parameters:
    test_bug_Embedded_BindNullsVarcharNonPrepared -- fails
    test_bug_Embedded_BindNullsVarchar
    test_bug_Embedded_BindNullsUnicode
    test_bug_Embedded_BindNullsVarcharInsert
    test_bug_Embedded_BindNullsUnicodeInsert

test_bug_Embedded_BindNullsVarcharNonPrepared is based on
test_bug_Embedded_BindNullsVarchar and fails presently, not sure if
this is an IngresDBI bug or an ODBC bug.

Fixed "bad" test NOtest_SimpleUnicodeBind, it has now been renamed to
test_SimpleUnicodeBind and is now part of all test runs.

Added new tests that do not run that show problems/hangs with/in
test_cursorIter when certain kinds of errors occur in previous tests.
    NOtest_anotherPreCursIter
    NOtest_iterhang_presetup

Warnings that list tests that do not run by default are now in sorted
order.

Updated test_stringUnicodeCharLongValues with possible DBMS problems 
information. Specifically problem with lengths from NCHAR casts.

Check for dbproc called lower was not checking the schema of the
current user which leed to dbproc failures if different users used
the same database for testing.

Linux Ubuntu 8.04.1 (LTS) Ingres 9.2 with Python 2.5.2
Windows XP Ingres 9.1.1 with Python 2.4.4 - note extra failures 
(failures=5, errors=2) due to Ingres DBMS bugs in 9.1.1


git-svn-id: http://code.ingres.com/ingres/drivers/python/main@1918 45b5d43f-8932-4c86-835a-3654e5842839